project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/urls.py
from django.urls import path
from . import views

app_name = 'recipes'

urlpatterns = [
    path('', views.home, name='home'),
    path('recipes/search/', views.search, name='search'),
    path('recipes/category/<int:category_id>/',
         views.category, name='category'),
    path('recipes/<int:id>/', views.recipe, name='recipe'),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=65)

    def __str__(self):
        return f"{self.name.capitalize()}"


# Create your models here.
class Recipe(models.Model):
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=10)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=10)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(
        upload_to='recipes/covers/%Y/%m/%d/', null=True, blank=True, default='')
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.title.capitalize()} - by {self.author.username}"

recipes/views.py
# Create your views here.
from django.http import Http404
from django.shortcuts import render, get_list_or_404, get_object_or_404
from django.db.models import Q
from .models import Recipe
from utils.pagination import make_view_pagination


def home(req):
    recipes = Recipe.objects.filter(is_published=True).order_by('-id')

    page_obj, pagination_range = make_view_pagination(req, recipes)

    return render(req, 'recipes/pages/home.html', context={
        'recipes': page_obj,
        'pagination_range': pagination_range
    })


def category(req, category_id):
    recipes = get_list_or_404(
        Recipe.objects.filter(
            category__id=category_id,
            is_published=True
        )
        .order_by('-id')
    )

    page_obj, pagination_range = make_view_pagination(req, recipes)

    return render(req, 'recipes/pages/category.html', context={
        'recipes': page_obj,  # get all recipes with this category
        'title': recipes[0].category.name,  # get category title
        'pagination_range': pagination_range
    })


def recipe(req, id):
    recipe = get_object_or_404(Recipe.objects, id=id, is_published=True)

    return render(req, 'recipes/pages/recipe-view.html', context={
        'recipe': recipe,
        'detail_page': True
    })


def search(req):
    search_term = req.GET.get('q', '').strip()
    if not search_term:
        raise Http404()

    recipes = Recipe.objects.filter(
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term)
        ), is_published=True

    ).order_by('-id')

    page_obj, pagination_range = make_view_pagination(req, recipes)

    return render(req, 'recipes/pages/search.html', context={
        'page_title': f'Search for "{search_term}"',
        'search_term': search_term,
        'recipes': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query': f'&q={search_term}'
    })

recipes/templates/recipes/pages/category.html
{% extends 'global/base.html' %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<div class="card-list">
  {% for recipe in recipes %}
  {% include 'recipes/partials/recipe.html' %}
  {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/home.html
{% extends 'global/base.html' %}

{% block title %}
Home
{% endblock title %}

{% block content %}
<div class='card-list'>
  {% for recipe in recipes %}
  {% include 'recipes/partials/recipe.html' %}
  {% empty %}
  <h1 style='font-family: Helvetica, sans-serif; text-align: center;'>
    Nenhuma receita encontrada 😢
  </h1>
  {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'global/base.html' %}
{% block title %}
{{recipe.title}}
{% endblock title %}
{% block content %}
<div class="card-detail">
  {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/pages/search.html
{% extends 'global/base.html' %}

{% block title %}
{{page_title}}
{% endblock title %}

{% block content %}

<div>
    <h3 class="search-query">Você buscou por {{search_term}}</h3>
</div>

<div class='card-list'>
    {% for recipe in recipes %}
    {% include 'recipes/partials/recipe.html' %}
    {% empty %}
    <h2>
        Nenhuma receita encontrada 😢
    </h2>
    {% endfor %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/footer.html
<footer>
    Made with <i style="color: rgb(226, 33, 33)" class="fa-solid fa-heart"></i> by Hícaro
    Vitor
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}

<meta charset="UTF-8" />
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<link rel="preconnect" href="https://fonts.googleapis.com" />
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;700&display=swap" rel="stylesheet" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/fontawesome.min.css"
  integrity="sha512-cHxvm20nkjOUySu7jdwiUxgGy11vuVPE9YeK89geLMLMMEOcKFyS2i+8wo0FOwyQO/bL8Bvq1KMsqK4bbOsPnA=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/brands.min.css"
  integrity="sha512-L+sMmtHht2t5phORf0xXFdTC0rSlML1XcraLTrABli/0MMMylsJi3XA23ReVQkZ7jLkOEIMicWGItyK4CAt2Xw=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/solid.min.css"
  integrity="sha512-bdTSJB23zykBjGDvyuZUrLhHD0Rfre0jxTd0/jpTbV7sZL8DCth/88aHX0bq2RV8HK3zx5Qj6r2rRU/Otsjk+g=="
  crossorigin="anonymous" referrerpolicy="no-referrer" />

<link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}" />
<link rel="stylesheet" href="{% static 'global/css/styles.css' %}" />

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
  <a class="main-logo" href="{% url 'recipes:home' %}">
    <span>Receitas</span>
    <i class="fa-solid fa-utensils"></i>
  </a>
</header>

recipes/templates/recipes/partials/pagination.html
{% if recipes.has_other_pages %}
<div class="content-pagination">
    {% if pagination_range.first_page_out_of_range %}
    <a class="page-item page-link" href="?page=1{{additional_url_query}}">1</a>
    <span class="page-item">...</span>
    {% endif %}

    {% for page in pagination_range.pagination %}
    {% if page == pagination_range.current_page %}
    <a class="page-item page-link current-page" href="?page={{page}}{{additional_url_query}}">{{page}}</a>
    {% else %}
    <a class="page-item page-link" href="?page={{page}}{{additional_url_query}}">{{page}}</a>
    {% endif %}
    {% endfor %}

    {% if pagination_range.last_page_out_of_range %}
    <span class="page-item">...</span>
    <a class="page-item page-link"
        href="?page={{pagination_range.total_pages}}{{additional_url_query}}">{{pagination_range.total_pages}}</a>
    {% endif %}
</div>
{% endif %}

recipes/templates/recipes/partials/recipe.html
<div class="card">
    <!-- get dynamic link using app_name:name in urls.py and send recipe.id as a parameter -->
    {% if recipe.cover %}
    <a href="{% url 'recipes:recipe' recipe.id %}">
        <img class="card-image" src="{{recipe.cover.url}}" alt="Random image" />
    </a>
    {% endif %}

    <h3 class="card-title">{{recipe.title}}</h3>

    <div class="info">
        <div class="recipe-author">
            <span class="recipe-author-item">
                <i class="fas fa-user"></i>
                {{recipe.author.username}}
            </span>
            <span class="recipe-author-item">
                <i class="fas fa-calendar-alt"></i>
                {{recipe.created_at|date:"d/m/Y à\s H:i"}}
            </span>
            {% if recipe.category is not None %}
            <span class="recipe-author-item">
                <a href="{% url 'recipes:category' recipe.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{recipe.category.name}}</span>
                </a>
            </span>
            {% endif %}
        </div>
    </div>

    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    {% if detail_page is not True %}
    <a class="card-footer" href="{% url 'recipes:recipe' recipe.id %}">
        <div class="card-button">
            <i class="fa-regular fa-eye"></i>
            Ver mais...
        </div>
    </a>
    {% else %}
    <p class="preparation-steps">
        {{recipe.preparation_steps|linebreaksbr}}
    </p>
    <div class="go-back"><a href="{% url 'recipes:home' %}">Voltar</a></div>
    {% endif %}
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
  <form action="{% url 'recipes:search' %}" method="get" class="search-form">
    <input class="search-input" type="text" name="q" id="search" value="{{search_term}}" required
      placeholder="Buscando por alguma receita? Digite aqui" />
    <button type="submit" class="search-button">
      <i class="fas fa-search"></i>
    </button>
  </form>
</div>